
---

# Vinicius Guerra e Ribas -  Energy Sector Analyst
[Energy Engineer (UnB)](https://www.unb.br/) │ [Data Scientist and Analytics (USP)](https://www5.usp.br/)


## [📧 E-mail](mailto:viniciusgribas@gmail.com?Subject=%5BANALISE-ESPACIAL-ANEEL%5D%20-%20Contact) │ [🎯 Linkedin](https://www.linkedin.com/in/vinicius-guerra-e-ribas/) │ [😸 GitHub](https://github.com/viniciusgribas) 

---

# [💻Project Notebook](https://github.com/viniciusgribas/Analise_dados_geracao_BR/blob/main/Analise_Geracao_I/Master_Code.ipynb) [🇧🇷] 

# [📃 Medium Post](https://viniciusgribas.medium.com/extraindo-insights-do-sistema-de-gera%C3%A7%C3%A3o-de-energia-el%C3%A9trica-brasileiro-utilizando-python-parte-i-70e3eb58c156) [🇧🇷]

In [127]:
### Importação de arquivos
# Realizando a importação das bibliotecas

# Bibliotecas padrão para tratamentos de DataFrames
import pandas as pd
import numpy as np
import chardet
import matplotlib
import matplotlib.pyplot as plt

# Bibliotecas para Integração API e Web Scrapping
import requests

# Bibliotecas padrão para tratamentos de GEO-DataFrames
import geopandas as gpd

# Apresentar os dados em mapas e gráficos
import plotly.express as px
import plotly as plt
import plotly.figure_factory as ff

# Selo pessoal para arquivos gerados

github = "_GitHub_@viniciusgribas.html"

In [128]:
# Extrair os arquivos via WebScrapping - integração API

patch = r"https://dadosabertos.aneel.gov.br/dataset/6d90b77c-c5f5-4d81-bdec-7bc619494bb9/resource/11ec447d-698d-4ab8-977f-b424d5deee6a/download/siga-empreendimentos-geracao.csv"

# Atribuição do caminho do arquivo solicitado

response_API = requests.get(patch)

# Verificar A disponibilidade do arquivo, caso o valor seja 200 obteve sucesso.

print(response_API.status_code)

# Verificar o informações sobre o endereço solicitado

print(response_API.headers)

## Destaque para as seguintes informações:
# 'Content-Type': 'text/csv'

# As informações a respeito do 'encoding' podem ser obtidas via comando .encoding

print(response_API.encoding)

200
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Wed, 20 Apr 2022 03:40:45 GMT', 'Content-Type': 'text/csv', 'Content-Length': '8039064', 'Connection': 'keep-alive', 'Last-Modified': 'Tue, 19 Apr 2022 20:13:45 GMT', 'Cache-Control': 'public, max-age=0, must-revalidate', 'Expires': 'Wed, 20 Apr 2022 15:40:45 GMT', 'ETag': '"1650399225.0924861-8039064-1145509437"'}
ISO-8859-1

In [129]:
# Uma vez verificado que o arquivo está em UTF-16, deve-se especifica-lo na funçao do pandas "pd.read_csv"
# Ao dataframe inicial, contendo os dados de geração do governo brasiliero será atribuído o nome de "df_ini"

df_ini = pd.read_csv(patch, sep= ";", header=0, decimal= ',',encoding="UTF-16" , )

# Visualizando o df_ini

df_ini

,DatGeracaoConjuntoDados,NomEmpreendimento,IdeNucleoCEG,CodCEG,SigUFPrincipal,SigTipoGeracao,DscFaseUsina,DscOrigemCombustivel,DscFonteCombustivel,DscTipoOutorga,...,MdaPotenciaFiscalizadaKw,MdaGarantiaFisicaKw,IdcGeracaoQualificada,NumCoordNEmpreendimento,NumCoordEEmpreendimento,DatInicioVigencia,DatFimVigencia,DscPropriRegimePariticipacao,DscSubBacia,DscMuninicpios
0,2022-04-19,E,8,PCH.PH.MG.000008-6.1,MG,PCH,Operação,Hídrica,Potencial hidráulico,Autorização,...,1400,0.0,Não,-20.124799,-43.870202,2000-07-07,2030-07-07,100% para ANGLOGOLD ASHANTI CÓRREGO DO SÍTIO M...,41 - Das Velhas - Sao Francisco,Nova Lima - MG
1,2022-04-19,F,9,PCH.PH.MG.000009-4.1,MG,PCH,Operação,Hídrica,Potencial hidráulico,Autorização,...,3972,0.0,Não,-20.131873,-43.876935,2000-07-07,2030-07-07,100% para ANGLOGOLD ASHANTI CÓRREGO DO SÍTIO M...,41 - Das Velhas - Sao Francisco,Nova Lima - MG
2,2022-04-19,G,10,PCH.PH.MG.000010-8.1,MG,PCH,Operação,Hídrica,Potencial hidráulico,Autorização,...,1440,0.0,Não,-20.137545,-43.891926,2000-08-31,2030-08-31,100% para ANGLOGOLD ASHANTI CÓRREGO DO SÍTIO M...,41 - Das Velhas - Sao Francisco,Nova Lima - MG
3,2022-04-19,14 de Julho,12,UHE.PH.RS.000012-4.1,RS,UHE,Operação,Hídrica,Potencial hidráulico,Concessão,...,100000,47500.0,Não,-29.064753,-51.674942,2001-03-15,2036-03-15,100% para COMPANHIA ENERGÉTICA RIO DAS ANTAS (...,86 - Taquari,"Bento Gonçalves - RS, Cotiporã - RS"
4,2022-04-19,Abaúna,15,CGH.PH.RS.000015-9.1,RS,CGH,Operação,Hídrica,Potencial hidráulico,Registro,...,720,510.0,Não,-27.823775,-52.069997,NaN,NaN,100% para Cooperativa de Geração de Energia e ...,"72 - Uruguai, Inhanduva, Peixe e outros",Floriano Peixoto - RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15464,2022-04-19,Sog001101_2277636,62058,UFV.RS.MS.062058-0.1,MS,UFV,Operação,Solar,Radiação solar,Registro,...,1,0.0,NaN,0.000000,0.000000,NaN,NaN,100% para ENERGISA MATO GROSSO DO SUL - DISTRI...,NaN,Corumbá - MS
15465,2022-04-19,Sog001102_2277638,62059,UFV.RS.MS.062059-9.1,MS,UFV,Operação,Solar,Radiação solar,Registro,...,1,0.0,NaN,0.000000,0.000000,NaN,NaN,100% para ENERGISA MATO GROSSO DO SUL - DISTRI...,NaN,Corumbá - MS
15466,2022-04-19,Sog001103_2277639,62060,UFV.RS.MS.062060-2.1,MS,UFV,Operação,Solar,Radiação solar,Registro,...,1,0.0,NaN,0.000000,0.000000,NaN,NaN,100% para ENERGISA MATO GROSSO DO SUL - DISTRI...,NaN,Corumbá - MS
15467,2022-04-19,Sog001104_2278238,62061,UFV.RS.MS.062061-0.1,MS,UFV,Operação,Solar,Radiação solar,Registro,...,1,0.0,NaN,0.000000,0.000000,NaN,NaN,100% para ENERGISA MATO GROSSO DO SUL - DISTRI...,NaN,Corumbá - MS
15468,2022-04-19,Sog001105_2278364,62062,UFV.RS.MS.062062-9.1,MS,UFV,Operação,Solar,Radiação solar,Registro,...,1,0.0,NaN,0.000000,0.000000,NaN,NaN,100% para ENERGISA MATO GROSSO DO SUL - DISTRI...,NaN,Corumbá - MS

In [130]:
# Percebe-se que existem observações (linhas) com valores "NaN" e variáveis (colunas) que não vão ser utilizadas nas análises.
# Portanto, é necessário trabalhar os dados. O que será feito na próxima etapa de Data Wrangling.

### Data Wrangling

In [131]:
# Primeiro, preserva-se o dataframe inicial "df_ini", realizando uma cópia deste.

df = df_ini.copy()

# Aqui se inicia a análise exploratória dos arquivos, a função ".info" permite 
# além de verificar as colunas, ver seu dtype.

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15469 entries, 0 to 15468
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   DatGeracaoConjuntoDados       15469 non-null  object
 1   NomEmpreendimento             15469 non-null  object
 2   IdeNucleoCEG                  15469 non-null  int64
 3   CodCEG                        15469 non-null  object
 4   SigUFPrincipal                15469 non-null  object
 5   SigTipoGeracao                15469 non-null  object
 6   DscFaseUsina                  15469 non-null  object
 7   DscOrigemCombustivel          15469 non-null  object
 8   DscFonteCombustivel           15469 non-null  object
 9   DscTipoOutorga                15469 non-null  object
 10  NomFonteCombustivel           15469 non-null  object
 11  DatEntradaOperacao            13618 non-null  object
 12  MdaPotenciaOutorgadaKw        15469 non-null  float64
 13  MdaPotenciaFiscalizadaKw      15469 non-null  int64
 14  MdaGarantiaFisicaKw           15469 non-null  float64
 15  IdcGeracaoQualificada         7187 non-null   object
 16  NumCoordNEmpreendimento       15469 non-null  float64
 17  NumCoordEEmpreendimento       15469 non-null  float64
 18  DatInicioVigencia             3939 non-null   object
 19  DatFimVigencia                3927 non-null   object
 20  DscPropriRegimePariticipacao  15469 non-null  object
 21  DscSubBacia                   1499 non-null   object
 22  DscMuninicpios                15469 non-null  object
dtypes: float64(4), int64(2), object(17)
memory usage: 2.7+ MB
None

In [132]:
# A função abaixo, permite verificar o nome atribuído a cada uma das colunas

print(df.columns.unique())

Index(['DatGeracaoConjuntoDados', 'NomEmpreendimento', 'IdeNucleoCEG',
       'CodCEG', 'SigUFPrincipal', 'SigTipoGeracao', 'DscFaseUsina',
       'DscOrigemCombustivel', 'DscFonteCombustivel', 'DscTipoOutorga',
       'NomFonteCombustivel', 'DatEntradaOperacao', 'MdaPotenciaOutorgadaKw',
       'MdaPotenciaFiscalizadaKw', 'MdaGarantiaFisicaKw',
       'IdcGeracaoQualificada', 'NumCoordNEmpreendimento',
       'NumCoordEEmpreendimento', 'DatInicioVigencia', 'DatFimVigencia',
       'DscPropriRegimePariticipacao', 'DscSubBacia', 'DscMuninicpios'],
      dtype='object')

In [133]:
# Realiza-se então a exclusão das que não serão utilizadas para esta análise

df = df.drop(columns=['DatGeracaoConjuntoDados','IdcGeracaoQualificada','IdeNucleoCEG','CodCEG','DscTipoOutorga','DatEntradaOperacao','MdaPotenciaFiscalizadaKw','MdaGarantiaFisicaKw','DatInicioVigencia','DatFimVigencia','DscPropriRegimePariticipacao','DscSubBacia','DscMuninicpios' ] )
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15469 entries, 0 to 15468
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NomEmpreendimento        15469 non-null  object
 1   SigUFPrincipal           15469 non-null  object
 2   SigTipoGeracao           15469 non-null  object
 3   DscFaseUsina             15469 non-null  object
 4   DscOrigemCombustivel     15469 non-null  object
 5   DscFonteCombustivel      15469 non-null  object
 6   NomFonteCombustivel      15469 non-null  object
 7   MdaPotenciaOutorgadaKw   15469 non-null  float64
 8   NumCoordNEmpreendimento  15469 non-null  float64
 9   NumCoordEEmpreendimento  15469 non-null  float64
dtypes: float64(3), object(7)
memory usage: 1.2+ MB

In [134]:
# -  NomEmpreendimento         Variável Qualitativa Nominal   
# -  SigUFPrincipal            Variável Qualitativa Nominal   
# -  DscAbreviacaoTipoGeracao  Variável Qualitativa Nominal   
# -  DscFaseUsina              Variável Qualitativa Ordinária   
# -  DscOrigemCombustivel      Variável Qualitativa Nominal   
# -  DscFonteCombustivel       Variável Qualitativa Nominal   
# -  NomFonteCombustivel       Variável Qualitativa Nominal   
# -   MdaPotenciaOutorgadaKw  Variável Quantitativa Contínua
# -  NumLatitude               Variável Qualitativa Ordinária   
# -  NumLongitude              Variável Qualitativa Ordinária

In [135]:
# Verifica-se as usinas que estão em operação, que estão em construção e 
# que ainda não foram iniciadas.

df.groupby("DscFaseUsina").count()

,NomEmpreendimento,SigUFPrincipal,SigTipoGeracao,DscOrigemCombustivel,DscFonteCombustivel,NomFonteCombustivel,MdaPotenciaOutorgadaKw,NumCoordNEmpreendimento,NumCoordEEmpreendimento
DscFaseUsina,,,,,,,,,
Construção,360,360,360,360,360,360,360,360,360
Construção não iniciada,1205,1205,1205,1205,1205,1205,1205,1205,1205
Operação,13904,13904,13904,13904,13904,13904,13904,13904,13904

In [136]:
# Filtra-se apenas as que estão em operação

df = df.query("DscFaseUsina == 'Operação'")
df.groupby("DscFaseUsina").count()

,NomEmpreendimento,SigUFPrincipal,SigTipoGeracao,DscOrigemCombustivel,DscFonteCombustivel,NomFonteCombustivel,MdaPotenciaOutorgadaKw,NumCoordNEmpreendimento,NumCoordEEmpreendimento
DscFaseUsina,,,,,,,,,
Operação,13904,13904,13904,13904,13904,13904,13904,13904,13904

In [137]:
# Aqui se gera uma tabela por 'DscOrigemCombustivel' com 
# valores totais (nulos e não nulos)


temp_a = df.groupby("DscOrigemCombustivel").sum()

print('============================TABELA DE VALORES TOTAIS====================================')

print(temp_a)



print('========================================================================================')

# Aqui se gera uma tabela por 'DscOrigemCombustivel' com valores nulos

print('============================TABELA DE VALORES NULOS====================================')
df[df.isnull().any(axis=1)]
df.isnull().sum()
# null_data = df[df.isnull().any(axis=1)]

# temp_b = null_data.groupby("DscOrigemCombustivel").sum()

# print(null_data)

# print('========================================================================================')

============================TABELA DE VALORES TOTAIS====================================
                      MdaPotenciaOutorgadaKw  NumCoordNEmpreendimento  \
DscOrigemCombustivel
Biomassa                        1.628338e+07            -11474.648572
Eólica                          2.162271e+07             -8582.018918
Fóssil                          3.022156e+07            -41615.341753
Hídrica                         1.094928e+08            -29367.919050
Nuclear                         1.990000e+06               -46.015919
Solar                           5.024255e+06            -16640.576885
Undi-Elétrica                   5.000000e+01                -3.532743

                      NumCoordEEmpreendimento
DscOrigemCombustivel
Biomassa                        -28791.886774
Eólica                          -33142.693345
Fóssil                         -122748.361970
Hídrica                         -68371.443535
Nuclear                            -88.916206
Solar                          -272715.109152
Undi-Elétrica                      -38.788790
========================================================================================
============================TABELA DE VALORES NULOS====================================

NomEmpreendimento          0
SigUFPrincipal             0
SigTipoGeracao             0
DscFaseUsina               0
DscOrigemCombustivel       0
DscFonteCombustivel        0
NomFonteCombustivel        0
MdaPotenciaOutorgadaKw     0
NumCoordNEmpreendimento    0
NumCoordEEmpreendimento    0
dtype: int64

In [138]:
# Verifica-se que o percentual dos valores Null, quando comparados com os totais, são muito baixos.

In [139]:
# # Aqui se gera uma tabela por 'DscOrigemCombustivel' com a representatividade 
# # dos valores nulos

# print('============================DIFERENÇA PERCENTUAL DE VALORES NULOS====================================')

# dif = (((temp_a-temp_b)/temp_a)*100)

# print(100 - dif )

In [173]:
# Verifica-se agora, por coluna os valores não nulos, 
# nulos e por fim se excluí os nulos desta análise.

print('=============== Contagem Total ===============')

print(df.count())

print('=============== Valores Nulos ===============')

print(df.isnull().sum())


print('=============== Após exclusão ===============')

print(df.dropna().count())


print(100 - dif )

# Atribui-se o nome de df_ger ao novo DF, sem valores null

df_ger = df.dropna().copy()

df_ger.head()

=============== Contagem Total ===============
NomEmpreendimento          13904
SigUFPrincipal             13904
SigTipoGeracao             13904
DscFaseUsina               13904
DscOrigemCombustivel       13904
DscFonteCombustivel        13904
NomFonteCombustivel        13904
MdaPotenciaOutorgadaKw     13904
NumCoordNEmpreendimento    13904
NumCoordEEmpreendimento    13904
dtype: int64
=============== Valores Nulos ===============
NomEmpreendimento          0
SigUFPrincipal             0
SigTipoGeracao             0
DscFaseUsina               0
DscOrigemCombustivel       0
DscFonteCombustivel        0
NomFonteCombustivel        0
MdaPotenciaOutorgadaKw     0
NumCoordNEmpreendimento    0
NumCoordEEmpreendimento    0
dtype: int64
=============== Após exclusão ===============
NomEmpreendimento          13904
SigUFPrincipal             13904
SigTipoGeracao             13904
DscFaseUsina               13904
DscOrigemCombustivel       13904
DscFonteCombustivel        13904
NomFonteCombustivel        13904
MdaPotenciaOutorgadaKw     13904
NumCoordNEmpreendimento    13904
NumCoordEEmpreendimento    13904
dtype: int64
                      IdeNucleoCEG  MdaPotenciaOutorgadaKw  \
DscOrigemCombustivel
Biomassa                       NaN                     NaN
Eólica                         NaN                     NaN
Fóssil                         NaN                     NaN
Hídrica                        NaN                     NaN
Nuclear                        NaN                     NaN
Solar                          NaN                     NaN
Undi-Elétrica                  NaN                     NaN

                      NumCoordNEmpreendimento  NumCoordEEmpreendimento
DscOrigemCombustivel
Biomassa                                  NaN                      NaN
Eólica                                    NaN                      NaN
Fóssil                                    NaN                      NaN
Hídrica                                   NaN                      NaN
Nuclear                                   NaN                      NaN
Solar                                     NaN                      NaN
Undi-Elétrica                             NaN                      NaN

,NomEmpreendimento,SigUFPrincipal,SigTipoGeracao,DscFaseUsina,DscOrigemCombustivel,DscFonteCombustivel,NomFonteCombustivel,MdaPotenciaOutorgadaKw,NumCoordNEmpreendimento,NumCoordEEmpreendimento
0,E,MG,PCH,Operação,Hídrica,Potencial hidráulico,Potencial hidráulico,1400.0,-20.124799,-43.870202
1,F,MG,PCH,Operação,Hídrica,Potencial hidráulico,Potencial hidráulico,3972.0,-20.131873,-43.876935
2,G,MG,PCH,Operação,Hídrica,Potencial hidráulico,Potencial hidráulico,1440.0,-20.137545,-43.891926
3,14 de Julho,RS,UHE,Operação,Hídrica,Potencial hidráulico,Potencial hidráulico,100000.0,-29.064753,-51.674942
4,Abaúna,RS,CGH,Operação,Hídrica,Potencial hidráulico,Potencial hidráulico,720.0,-27.823775,-52.069997

In [174]:
df_ger.columns

Index(['NomEmpreendimento', 'SigUFPrincipal', 'SigTipoGeracao', 'DscFaseUsina',
       'DscOrigemCombustivel', 'DscFonteCombustivel', 'NomFonteCombustivel',
       'MdaPotenciaOutorgadaKw', 'NumCoordNEmpreendimento',
       'NumCoordEEmpreendimento'],
      dtype='object')

In [175]:
# Modificando o nome das colunas do DF

df_ger = df_ger.rename( columns ={
"NomEmpreendimento":"Empreendimento",
"SigUFPrincipal":"UF",
"SigTipoGeracao":"TipoGeracao",
"DscFaseUsina":"Fase",
"DscOrigemCombustivel":"OrigemCombustivel",
"DscFonteCombustivel":"FonteCombustivel",
"NomFonteCombustivel":"NomeCombustivel",
"MdaPotenciaOutorgadaKw":"MdaPotenciaOutorgadaKW",
"NumCoordEEmpreendimento": "X",
"NumCoordNEmpreendimento": "Y",	
"DscMuninicpios":"Municipio"
})

df_ger.columns

Index(['Empreendimento', 'UF', 'TipoGeracao', 'Fase', 'OrigemCombustivel',
       'FonteCombustivel', 'NomeCombustivel', 'MdaPotenciaOutorgadaKW', 'Y',
       'X'],
      dtype='object')

In [176]:


# Definindo as variáveis de latitude (Y) e longitude(X) como float

df_ger['X'] = df_ger['X'].apply(lambda col:pd.to_numeric(col, errors='coerce'))
df_ger['Y'] = df_ger['Y'].apply(lambda col:pd.to_numeric(col, errors='coerce'))

# Criando um Dataframe Geográfico a partir do DF antigo

gdf_ger = gpd.GeoDataFrame(
    df_ger, geometry=gpd.points_from_xy(df_ger.X, df_ger.Y))

# Determinando um CRS para o novo DF Geográfico

gdf_ger.crs = "EPSG:5880" 

df_ger.head()

# Com os dados minimamente lapidados, agora é possível iniciar as fases de 
# Análises Exporatórias Geoespaciais na geometria ponto

,Empreendimento,UF,TipoGeracao,Fase,OrigemCombustivel,FonteCombustivel,NomeCombustivel,MdaPotenciaOutorgadaKW,Y,X,geometry
0,E,MG,PCH,Operação,Hídrica,Potencial hidráulico,Potencial hidráulico,1400.0,-20.124799,-43.870202,POINT (-43.870 -20.125)
1,F,MG,PCH,Operação,Hídrica,Potencial hidráulico,Potencial hidráulico,3972.0,-20.131873,-43.876935,POINT (-43.877 -20.132)
2,G,MG,PCH,Operação,Hídrica,Potencial hidráulico,Potencial hidráulico,1440.0,-20.137545,-43.891926,POINT (-43.892 -20.138)
3,14 de Julho,RS,UHE,Operação,Hídrica,Potencial hidráulico,Potencial hidráulico,100000.0,-29.064753,-51.674942,POINT (-51.675 -29.065)
4,Abaúna,RS,CGH,Operação,Hídrica,Potencial hidráulico,Potencial hidráulico,720.0,-27.823775,-52.069997,POINT (-52.070 -27.824)

### Análises Exploratórias no GeoDataFrame *[Geometria - Ponto]*

In [177]:
# Contando quantos empreendimentos existem em operação, para verificar se condiz 
# com o relatório disponibilizado plea ANEEL original (2021)

df_ger.groupby('TipoGeracao').count()

,Empreendimento,UF,Fase,OrigemCombustivel,FonteCombustivel,NomeCombustivel,MdaPotenciaOutorgadaKW,Y,X,geometry
TipoGeracao,,,,,,,,,,
CGH,737,737,737,737,737,737,737,737,737,737
CGU,1,1,1,1,1,1,1,1,1,1
EOL,812,812,812,812,812,812,812,812,812,812
PCH,432,432,432,432,432,432,432,432,432,432
UFV,8590,8590,8590,8590,8590,8590,8590,8590,8590,8590
UHE,218,218,218,218,218,218,218,218,218,218
UTE,3112,3112,3112,3112,3112,3112,3112,3112,3112,3112
UTN,2,2,2,2,2,2,2,2,2,2

In [178]:
#### Diagrama de Barras Iterativo ####

# Titulo

title_BarChart = "Diagrama de Barras:Potência Outorgada [KW] e Tipo de Geração por UF" 

# Titulo para exportar o arquivo em html

title_BarChart_export = "Bar"+github

# Função para criar a variável do gráfico de barrras iterativo do plotfy

fig_BarChart = px.bar(df_ger, # Dataframe
 x="UF",                      # Variável Qualitativa Nominal
 y="MdaPotenciaOutorgadaKW",  # Variável Quantitativa Contínua
 color="TipoGeracao",         # Variável Qualitativa Nominal
 title=title_BarChart,        # Título
 width=800,                   # Largura
 height=1000                 # Altura
)

# Função para Plotagem do plotfy

fig_BarChart.show()           

# Função do plotfy para exportar o gráfico em HTML e salva-lo

plt.offline.plot(fig_BarChart, filename = title_BarChart_export)

'Bar_GitHub_@viniciusgribas.html'

In [179]:
    #### Diagrama de Barras Iterativo ####

    # Titulo

    title_BarChart = "Diagrama de Barras:Potência Outorgada [KW] e UF por Tipo de Geracao" 

    # Titulo para exportar o arquivo em html

    title_BarChart_export = "Bar2"+github

    # Função para criar a variável do gráfico de barrras iterativo do plotfy

    fig_BarChart = px.bar(df_ger, # Dataframe
    x="TipoGeracao",             # Variável Qualitativa Nominal
    y="MdaPotenciaOutorgadaKW",  # Variável Quantitativa Contínua
    color="UF",         # Variável Qualitativa Nominal
    title=title_BarChart,        # Título
    width=800,                   # Largura
    height=1000                 # Altura
    )

    # Função para Plotagem do plotfy

    fig_BarChart.show()           

    # Função do plotfy para exportar o gráfico em HTML e salva-lo

    plt.offline.plot(fig_BarChart, filename = title_BarChart_export)

'Bar2_GitHub_@viniciusgribas.html'

In [180]:
#### Diagrama de Pontos Iterativo ####

# Titulo

title_strip = "Diagrama de Pontos:Potência Outorgada [KW] e Tipo de Geração por UF"

# Titulo para exportar o arquivo em html

title_strip_export = "Strip"+github

# Função para criar a variável do gráfico de pontos iterativo do plotfy

fig_Strip = px.strip(df_ger,  # Dataframe
 title=title_strip,           # Titulo
 x="MdaPotenciaOutorgadaKW",  # Variável Quantitativa Contínua
 y="UF",                      # Variável Qualitativa Nominal
 orientation="h",             # Orientação Horizontal
 hover_name="Empreendimento", # Nome do empreendimento
 color="TipoGeracao",      # Variável Qualitativa Nominal
)

# Função para Plotagem do plotfy

fig_Strip.show()

# Função do plotfy para exportar o gráfico em HTML e salva-lo

plt.offline.plot(fig_Strip, filename = title_strip_export)

'Strip_GitHub_@viniciusgribas.html'

In [181]:
#### Diagrama Polar Iterativo ####

# Titulo

title_Polar = "Diagrama Polar: Potência Outorgada[KW] e UF por Tipo de Geração"

# Titulo para exportar o arquivo em html

title_Polar_export = "Polar"+github

# Função para criar a variável do gráfico de pontos iterativo do plotfy

fig_Polar = px.bar_polar(df_ger, # Dataframe
 title=title_Polar,              # Titulo
 r="MdaPotenciaOutorgadaKW",     # Variável Quantitativa Contínua
 theta="UF",                     # Variável Qualitativa Nominal
 color="MdaPotenciaOutorgadaKW", # Variável Quantitativa Contínua
 template="plotly",              # Opção de Cores pré-definidas pelo plotfy
 animation_frame="TipoGeracao",  # Variável Qualitativa Nominal
 hover_name= 'Empreendimento',
 color_discrete_sequence= px.colors.sequential.Plasma_r # Opção de Cores pré-definidas pelo plotfy
) 

# Função para Plotagem do plotfy

fig_Polar.show()

# Função do plotfy para exportar o gráfico em HTML e salva-lo

plt.offline.plot(fig_Polar, filename = title_Polar_export)

'Polar_GitHub_@viniciusgribas.html'

In [182]:
#### Diagrama de Densindade e Barras Iterativo ####

# Titulo

title_Densidade = "Diagrama Densidade e Barras: UF por Tipo de Geração"

# Titulo para exportar o arquivo em html

title_Densidade_export = "Densidade"+github

# Função para criar a variável do gráfico de pontos iterativo do plotfy

fig_dens = px.density_heatmap(df_ger,  # Dataframe
 title=title_Densidade,                # Titulo
 x="UF",                               # Variável Qualitativa Nominal
 y="TipoGeracao",                      # Variável Qualitativa Nominal
 z= "MdaPotenciaOutorgadaKW" ,         # Variável Quantitativa Contínua
 marginal_x="histogram",               # Tipo de diagrama adicional para o eixo X
 marginal_y="histogram",               # Tipo de diagrama adicional para o eixo Y
 text_auto=True                        # Contagem para cada uma das células
)

# Função para Plotagem do plotfy

fig_dens.show()

# Função do plotfy para exportar o gráfico em HTML e salva-lo

plt.offline.plot(fig_dens, filename = title_Densidade_export)

'Densidade_GitHub_@viniciusgribas.html'

In [183]:
#### Diagrama de Densindade e Barras Iterativo ####

# Titulo

title_Densidade = "Diagrama Densidade e Barras: Origem Combustível por Tipo de Geração"

# Titulo para exportar o arquivo em html

title_Densidade_export = "Densidade_2"+github

# Função para criar a variável do gráfico de pontos iterativo do plotfy

fig_dens = px.density_heatmap(df_ger,  # Dataframe
 title=title_Densidade,                # Titulo
 x="OrigemCombustivel",                # Variável Qualitativa Nominal
 y="TipoGeracao",                      # Variável Qualitativa Nominal
 z='MdaPotenciaOutorgadaKW',           # Variável Quantitativa Contínua
 marginal_x="histogram",               # Tipo de diagrama adicional para o eixo X
 marginal_y="histogram",               # Tipo de diagrama adicional para o eixo Y
 text_auto=True                        # Contagem para cada uma das células
)

# Função para Plotagem do plotfy

fig_dens.show()

# Função do plotfy para exportar o gráfico em HTML e salva-lo

plt.offline.plot(fig_dens, filename = title_Densidade_export)

'Densidade_2_GitHub_@viniciusgribas.html'

In [184]:
#### Diagrama de Densindade e Barras Iterativo ####

# Titulo

title_Densidade = "Diagrama Densidade e Barras: UF por Tipo de Geração"

# Titulo para exportar o arquivo em html

title_Densidade_export = "Densidade_3"+github

# Função para criar a variável do gráfico de pontos iterativo do plotfy

fig_dens = px.density_heatmap(df_ger,  # Dataframe
 title=title_Densidade,                # Titulo
 x="UF",                               # Variável Qualitativa Nominal
 y="TipoGeracao",                      # Variável Qualitativa Nominal
 #z= "MdaPotenciaOutorgadaKW" ,           # Variável Quantitativa Contínua
 marginal_x="histogram",               # Tipo de diagrama adicional para o eixo X
 marginal_y="histogram",               # Tipo de diagrama adicional para o eixo Y
 text_auto=True                        # Contagem para cada uma das células
)

# Função para Plotagem do plotfy

fig_dens.show()

# Função do plotfy para exportar o gráfico em HTML e salva-lo

plt.offline.plot(fig_dens, filename = title_Densidade_export)

'Densidade_3_GitHub_@viniciusgribas.html'

In [185]:
#### Mapa Iterativo de Coordenadas Cartesianas  ####

# Titulo

title_pointsMap = "Mapa de Coordenadas: Potência Outorgada por Localização do Empreendimento"

# Titulo para exportar o arquivo em html

title_pointsMap_export = "Points"+github

# Função para criar a variável do gráfico de pontos iterativo do plotfy

fig_pointsMap = px.scatter_mapbox(df_ger,              # DataFrame
 title=title_pointsMap,                                # Titulo
 lat="Y",                                              # Variável do tipo Float Referente à Latitude
 lon="X",                                              # Variável do tipo Float Referente à Longitude
 color="MdaPotenciaOutorgadaKW",                       # Variável Quantitativa Contínua atribuída à cor
 size="MdaPotenciaOutorgadaKW",                        # Variável Quantitativa Contínua atribuída ao tamanho dos círculos
 color_continuous_scale=px.colors.sequential.matter,   # Opção de Cores pré-definidas pelo plotfy
 hover_name = "Empreendimento" ,                       # Apresentar o nome do empreendimento na caixa iterativa
 hover_data = ["MdaPotenciaOutorgadaKW"],              # Variável Quantitativa Contínua atribuída à função
 size_max=80,                                          # Tamanho máximo para os círculos
 zoom=3,                                               # Zoom inicial no mapa
 mapbox_style='open-street-map',                       # Opção de Mapa pré definida pelo plotfy
 animation_frame='TipoGeracao'                         # Variável Qualitativa Atribuída à animação do mapa (Vai dividi-lo)
)

# Função para Plotagem do plotfy

fig_pointsMap.show()

# Função do plotfy para exportar o gráfico em HTML e salva-lo

plt.offline.plot(fig_pointsMap, filename = title_pointsMap_export)

'Points_GitHub_@viniciusgribas.html'